blank_issues_enabled: true

contact_links:
  - name: Discord Server
    about: If you need usage assistance or want to ask a question then you can join my Discord server.
    url: https://viral32111.com/discord

  - name: Contact Me
    about: If you have a question you wish to ask privately or a confidential report to submit then email me.
    url: https://viral32111.com/contact
