name: Release

on:
  push:
    branches-ignore:
      - main
    tags:
      - '*'

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Get Tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}

      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:latest
            docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ steps.get_tag.outputs.tag }}

  github:
    name: GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Get Tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Create Draft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: ${{ steps.get_tag.outputs.tag }}
          body: ${{ github.event.head_commit.message }}
          draft: true
